CSC207-2022F-UofT/course-project-team-java-help

.github/workflows/test.yml
Add a CI workflow to run all tests on push.
=> setup testing ci workflow

.idea/misc.xml, build.gradle
Switch Android Gradle Plugin version for compatibility
=> update to non-beta gradle plugin

model/src/main/java/com/javahelp/model/survey/Survey.java, model/src/main/java/com/javahelp/model/survey/SurveyQuestion.java, model/src/main/java/com/javahelp/model/survey/SurveyQuestionResponse.java, model/src/main/java/com/javahelp/model/survey/SurveyResponse.java, model/src/test/java/com/javahelp/model/survey/SurveyQuestionResponseTest.java, model/src/test/java/com/javahelp/model/survey/SurveyQuestionTest.java, model/src/test/java/com/javahelp/model/survey/SurveyResponseTest.java, model/src/test/java/com/javahelp/model/survey/SurveyTest.java
Add survey entities (`Survey`, `SurveyQuestion`, `SurveyQuestionResponse`, `SurveyResponse`) and associated tests. Closes #10.
=> Survey entities

serverless.yml
=> add cloudformation templates for dynamodb tables to serverless.yml

backend/build.gradle, backend/src/main/java/com/javahelp/backend/Handler.java, serverless.yml
Setup the now configured DynamoDB to work with the AWS Lambda functions created by the Serverless library for this application. Configure the backend module to use the AWS Java SDK to connect to DynamoDB.
=> Setup DynamoDB Client

.github/workflows/deploy.yml, .github/workflows/test.yml, backend/build.gradle, backend/src/main/java/com/javahelp/backend/Handler.java, backend/src/main/java/com/javahelp/backend/core/gateway/ICRUDGateway.java, backend/src/main/java/com/javahelp/backend/data/DynamoDBStore.java, backend/src/main/java/com/javahelp/backend/data/ICRUDGateway.java, serverless.yml
Closes #46. Specifies a CRUD interface for simple database interactions, also add Dynamo authentication to Github Actions test workflows for eventual Dynamo interacting tests. Depends on #40, cannot be merged before this is closed.
=> Crud interface

backend/src/main/java/com/javahelp/backend/auth/ITokenStore.java, backend/src/main/java/com/javahelp/backend/data/ICRUDGateway.java, backend/src/main/java/com/javahelp/backend/data/ITokenStore.java, model/src/main/java/com/javahelp/model/token/Token.java, model/src/test/java/com/javahelp/model/token/TokenTest.java
Closes #42. Branched off #51 and #46, should only be merged after both.
=> Token gateway

backend/src/main/java/com/javahelp/backend/data/IUserStore.java, model/src/main/java/com/javahelp/model/user/UserPassword.java, model/src/test/java/com/javahelp/model/user/UserPasswordTest.java
=> User gateway

backend/src/main/java/com/javahelp/backend/data/DynamoDBTokenStore.java, backend/src/main/java/com/javahelp/backend/data/ITokenStore.java, backend/src/test/java/com/javahelp/backend/data/DynamoDBTokenStoreTest.java, model/src/main/java/com/javahelp/model/token/Token.java
Closes #41. Implements the ITokenStore interface through DynamoDB
=> Implement token gateway

backend/src/main/java/com/javahelp/backend/data/DynamoDBUserStore.java, backend/src/main/java/com/javahelp/backend/data/IUserStore.java, backend/src/test/java/com/javahelp/backend/data/DynamoDBUserStoreTest.java, model/src/main/java/com/javahelp/model/user/UserPassword.java, model/src/test/java/com/javahelp/model/user/UserPasswordTest.java
=> Implement user gateway

model/src/main/java/com/javahelp/model/user/IPasswordHasher.java, model/src/main/java/com/javahelp/model/user/SHAPasswordHasher.java, model/src/main/java/com/javahelp/model/user/UserPassword.java, model/src/test/java/com/javahelp/model/user/SHAPasswordHasherTest.java
=> Password hasher

backend/src/main/java/com/javahelp/backend/data/DynamoDBUserStore.java, backend/src/test/java/com/javahelp/backend/data/DynamoDBUserStoreTest.java
=> Login dynamo

app/src/main/AndroidManifest.xml, app/src/main/java/com/javahelp/frontend/ClientRegistrationActivity.java, app/src/main/java/com/javahelp/frontend/MainActivity.java, app/src/main/res/layout/activity_client_registration.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_preg.xml, app/src/main/res/values/themes.xml
I added client registration activity, and changed some of the style. I also added back arrow.
=> Add the client registration activity, edit the style of UI.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/javahelp/frontend/ClientRegistrationActivity.java, app/src/main/java/com/javahelp/frontend/ClientRegistrationVm.java, app/src/main/java/com/javahelp/frontend/FrontPage2Activity.java, app/src/main/java/com/javahelp/frontend/MainActivity.java, app/src/main/java/com/javahelp/frontend/MyViewModel.java, app/src/main/java/com/javahelp/frontend/ProviderRegistrationActivity.java, app/src/main/java/com/javahelp/frontend/ProviderRegistrationViewmodel.java, app/src/main/res/layout/activity_client_registration.xml, app/src/main/res/layout/activity_front_page2.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_preg.xml
Set viewmodel for current activities and added data binding feature to help organize the data and make the activities cleaner.
=> viewmodel_SETUP

backend/src/main/java/com/javahelp/backend/domain/user/authentication/ISaltInput.java, backend/src/main/java/com/javahelp/backend/domain/user/authentication/SaltInteractor.java, backend/src/main/java/com/javahelp/backend/domain/user/authentication/SaltResult.java, backend/src/main/java/com/javahelp/backend/endpoint/APIGatewayResponse.java, backend/src/main/java/com/javahelp/backend/endpoint/APIGatewayV2ProxyRequestEvent.java, backend/src/main/java/com/javahelp/backend/endpoint/HTTPHandler.java, backend/src/main/java/com/javahelp/backend/endpoint/login/LoginHandler.java, backend/src/main/java/com/javahelp/backend/endpoint/login/SaltHandler.java, backend/src/test/java/com/javahelp/backend/domain/user/authentication/SaltInteractorTest.java, backend/src/test/java/com/javahelp/backend/endpoint/login/SaltHandlerTest.java, serverless.yml
=> Salt handler

backend/src/main/java/com/javahelp/backend/endpoint/APIGatewayResponse.java, backend/src/main/java/com/javahelp/backend/endpoint/HTTPTokenHandler.java
Misc fixes to resolve handler conflict and make all request codes constant.
=> Fix handlers path params

app/src/main/AndroidManifest.xml, app/src/main/java/com/javahelp/frontend/LoginActivity.java, app/src/main/java/com/javahelp/frontend/LoginViewModel.java, app/src/main/java/com/javahelp/frontend/MainActivity.java, app/src/main/java/com/javahelp/frontend/MyViewModel.java, app/src/main/java/com/javahelp/frontend/domain/user/login/ILoginDataAccess.java, app/src/main/java/com/javahelp/frontend/domain/user/login/ILoginInput.java, app/src/main/java/com/javahelp/frontend/domain/user/login/ILoginOutput.java, app/src/main/java/com/javahelp/frontend/domain/user/login/ISaltDataAccess.java, app/src/main/java/com/javahelp/frontend/domain/user/login/LoginInteractor.java, app/src/main/java/com/javahelp/frontend/domain/user/login/LoginResult.java, app/src/main/java/com/javahelp/frontend/gateway/LambdaLoginDataAccess.java, app/src/main/java/com/javahelp/frontend/gateway/LambdaSaltDataAccess.java, app/src/main/java/com/javahelp/frontend/gateway/RESTAPIGateway.java, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_main.xml, app/src/test/java/com/javahelp/frontend/domain/user/login/LoginInteractorTest.java, backend/src/main/java/com/javahelp/backend/domain/user/authentication/SaltInteractor.java, backend/src/main/java/com/javahelp/backend/domain/user/authentication/TokenAuthManager.java, backend/src/test/java/com/javahelp/backend/domain/user/authentication/TokenAuthManagerTest.java
=> Login frontend

README.md
This adds execution instructions, testing instructions, API reference, and locations to download the compiled APKs to the README.
=> Milestone 4 Submission Changes

.gitignore, backend/src/main/java/com/javahelp/backend/domain/user/delete/DeleteManager.java, backend/src/main/java/com/javahelp/backend/domain/user/delete/DeleteResult.java, backend/src/main/java/com/javahelp/backend/domain/user/delete/IDeleteInputBoundary.java, backend/src/main/java/com/javahelp/backend/endpoint/HTTPTokenHandler.java, backend/src/main/java/com/javahelp/backend/endpoint/delete/DeleteHandler.java, backend/src/test/java/com/javahelp/backend/domain/user/delete/DeleteManagerTest.java, backend/src/test/java/com/javahelp/backend/endpoint/delete/DeleteHandlerTest.java, serverless.yml
The handler for an account deletion.
=> [Backend] Account Deletion Handler

backend/src/main/java/com/javahelp/backend/domain/user/register/IUserRegisterInputBoundary.java, backend/src/main/java/com/javahelp/backend/domain/user/register/RegisterUserResponse.java, backend/src/main/java/com/javahelp/backend/domain/user/register/UserRegisterInteractor.java, backend/src/main/java/com/javahelp/backend/domain/user/register/UserRegisterResult.java, backend/src/main/java/com/javahelp/backend/domain/user/register/client/ClientRegisterInteractor.java, backend/src/main/java/com/javahelp/backend/domain/user/register/client/IClientRegisterInputBoundary.java, backend/src/main/java/com/javahelp/backend/domain/user/register/provider/IProviderRegisterInputBoundary.java, backend/src/main/java/com/javahelp/backend/domain/user/register/provider/ProviderRegisterInteractor.java, backend/src/test/java/com/javahelp/backend/domain/user/register/ClientRegisterTest.java, backend/src/test/java/com/javahelp/backend/domain/user/register/ProviderRegisterTest.java
A backend register user use case for all types of `users`, such as for `clients` and `providers`
=> User register for both Clients and Providers
